### ISSUE TITLE
help page shows empty results

### ISSUE THREAD

**Issue by chunhualiao** [ouankou/rose-demo-docker#7]
1. goto http://demo.rosecompiler.org/getValues.html?tool=dotGeneratorWholeASTGraph

2, click copy/past text 

3 then click "Manua"l link in the bottom.  the manual page returns empty results.  It is designed to show the output of --help of the tool selected. 

<img width="741" alt="Screen Shot 2020-06-10 at 10 37 35 AM" src="https://user-images.githubusercontent.com/1627206/84299919-6c19b900-ab06-11ea-84db-9f9f0fd6218d.png">

**Comment by World-Worst-Detector** [comment]
It was fixed. Check at http://demo.rosecompiler.org/cgi-bin/help_page.sh.

**Comment by World-Worst-Detector** [comment]
Sry,You need go through this page first http://demo.rosecompiler.org/getValues.html?tool=dotGeneratorWholeASTGraph.

**Comment by chunhualiao** [comment]
@Yaying-llnl-summer Can you elaborate how you fixed it?  It is best to show details using a diff or a git commit when reporting a fix.  So the fix can be reviewed by others before closing a ticket.

**Comment by Yaying-llnl-summer** [comment]
This issue was cauzed by miss directory in help_page.sh. You can track the issue by check the /tmp directory. There are some log file named hlep_time.log for you track the issue. Then you will find the problem was caused by line 211: Final_Command="$roseTranslator --help &> /tmp/man_pages/manual_${tool}.txt".
Then you just need change the script as following instruction:
https://github.com/ouankou/rose-demo-docker/commit/b47353b5be98070d89c67f87327d8807bf4dd04d#diff-16f0d91fa8afd0d937d5840c7670e6e2
