### ISSUE TITLE
add a new tool into the website

### ISSUE THREAD

**Issue by chunhualiao** [ouankou/rose-demo-docker#8]
The tool is named preprocessingInfoDumper 

More info.

https://en.wikibooks.org/wiki/ROSE_Compiler_Framework/PreprocessingInfo#the_builtin_preprocessingInfoDumper

**Comment by Yaying-llnl-summer** [comment]
To add new tools, first test the command line to use tool as following:  preprocessingInfoDumper -c code1.c. Then, check the runtool.sh, if you need make some change for special tools. Since command for preprocess info is a standard one, we don't have to change the runtool.sh. The next step is update the web interface.
1. add preprocessingInfoDumper in index.html
2. add example code for preprocessingInfoDumper in getValue.html.
Then detail change can be tracked here:
https://github.com/ouankou/rose-demo-docker/commit/0ae9567590ef5c4c4465f74a4865597b38d5f77c
